<?php

namespace App\Http\Controllers;

class DownloadController extends Controller
{
    public function index()
    {
        $downloads = [
            [
                'id' => 1,
                'title' => 'تعريفات طابعات HP - حزمة شاملة',
                'description' => 'حزمة تعريفات شاملة لجميع طابعات HP LaserJet و OfficeJet. متوافقة مع Windows 10/11.',
                'category' => 'تعريفات',
                'brand' => 'HP',
                'version' => '2.5.1',
                'size' => '145 MB',
                'date' => '2026-04-01',
                'downloads' => 12450,
                'os' => 'Windows 10/11',
                'icon' => 'fa-print',
            ],
            [
                'id' => 2,
                'title' => 'تعريفات طابعات Canon PIXMA',
                'description' => 'تعريفات رسمية لطابعات Canon PIXMA G-Series. تشمل برامج الطباعة والمسح الضوئي.',
                'category' => 'تعريفات',
                'brand' => 'Canon',
                'version' => '3.2.0',
                'size' => '98 MB',
                'date' => '2026-03-28',
                'downloads' => 8920,
                'os' => 'Windows 10/11',
                'icon' => 'fa-print',
            ],
            [
                'id' => 3,
                'title' => 'تعريفات طابعات Epson EcoTank',
                'description' => 'تعريفات وبرامج مساعدة لطابعات Epson EcoTank. تدعم الطباعة اللاسلكية والطباعة من الهاتف.',
                'category' => 'تعريفات',
                'brand' => 'Epson',
                'version' => '4.1.2',
                'size' => '112 MB',
                'date' => '2026-03-25',
                'downloads' => 7650,
                'os' => 'Windows 10/11',
                'icon' => 'fa-print',
            ],
            [
                'id' => 4,
                'title' => 'تعريفات طابعات Brother',
                'description' => 'حزمة تعريفات كاملة لطابعات Brother HL و DCP و MFC. تشمل برامج الإدارة والصيانة.',
                'category' => 'تعريفات',
                'brand' => 'Brother',
                'version' => '2.8.5',
                'size' => '87 MB',
                'date' => '2026-03-20',
                'downloads' => 5430,
                'os' => 'Windows 10/11',
                'icon' => 'fa-print',
            ],
            [
                'id' => 5,
                'title' => 'برنامج HP Smart - إدارة الطابعات',
                'description' => 'تطبيق رسمي من HP لإدارة الطابعات والطباعة من الهاتف والمسح الضوئي السحابي.',
                'category' => 'برامج',
                'brand' => 'HP',
                'version' => '8.12.0',
                'size' => '156 MB',
                'date' => '2026-04-10',
                'downloads' => 23400,
                'os' => 'Windows 10/11',
                'icon' => 'fa-mobile-alt',
            ],
            [
                'id' => 6,
                'title' => 'برنامج Epson Print Layout',
                'description' => 'برنامج احترافي لطباعة الصور بجودة عالية على طابعات Epson. مثالي للمصورين.',
                'category' => 'برامج',
                'brand' => 'Epson',
                'version' => '1.6.3',
                'size' => '64 MB',
                'date' => '2026-03-15',
                'downloads' => 4320,
                'os' => 'Windows 10/11',
                'icon' => 'fa-image',
            ],
            [
                'id' => 7,
                'title' => 'دليل المستخدم - طابعات HP LaserJet Pro',
                'description' => 'دليل شامل باللغة العربية لاستخدام وصيانة طابعات HP LaserJet Pro Series.',
                'category' => 'أدلة',
                'brand' => 'HP',
                'version' => '1.0',
                'size' => '12 MB',
                'date' => '2026-02-01',
                'downloads' => 6780,
                'os' => 'PDF',
                'icon' => 'fa-file-pdf',
            ],
            [
                'id' => 8,
                'title' => 'دليل استكشاف الأخطاء - Canon PIXMA',
                'description' => 'دليل مفصل لحل المشاكل الشائعة في طابعات Canon PIXMA. يشمل رموز الأخطاء والحلول.',
                'category' => 'أدلة',
                'brand' => 'Canon',
                'version' => '2.0',
                'size' => '8 MB',
                'date' => '2026-01-15',
                'downloads' => 5120,
                'os' => 'PDF',
                'icon' => 'fa-file-pdf',
            ],
            [
                'id' => 9,
                'title' => 'برنامج Logitech Options+',
                'description' => 'برنامج تخصيص الماوسات ولوحات المفاتيح من Logitech. يدعم جميع الموديلات الحديثة.',
                'category' => 'برامج',
                'brand' => 'Logitech',
                'version' => '1.52.0',
                'size' => '178 MB',
                'date' => '2026-04-15',
                'downloads' => 18900,
                'os' => 'Windows 10/11',
                'icon' => 'fa-mouse',
            ],
            [
                'id' => 10,
                'title' => 'كتالوج المنتجات 2026',
                'description' => 'كتالوج شامل لجميع منتجات MJK لعام 2026 مع الأسعار والمواصفات التفصيلية.',
                'category' => 'كتالوجات',
                'brand' => 'MJK',
                'version' => '2026',
                'size' => '24 MB',
                'date' => '2026-01-01',
                'downloads' => 15670,
                'os' => 'PDF',
                'icon' => 'fa-book',
            ],
        ];

        $categories = array_unique(array_column($downloads, 'category'));
        $brands = array_unique(array_column($downloads, 'brand'));

        return view('downloads.index', compact('downloads', 'categories', 'brands'));
    }
}
